# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ImAKappa 
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Website of ImAKappa. Free sheet music for piano.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imakappa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: /./assets/images/imakappa-channel-logo-2020.png
twitter:
  username: imakappa1
  card: summary
social:
  name: Alex Kappen
  links:
    - https://twitter.com/imakappa1
    - https://www.youtube.com/channel/UC-ij-Y_86B9H1ARnaxnhEtw
    - https://github.com/ImAKappa
lang: en_US

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - 
    scope:
      path: "sheet-music"
      type: "posts"
    values:
      layout: "sheets-layout"
      permalink: ":categories/:title"
      pdf-lyric: "#"
      yt-link: "#"
      muse-link: "#"
  - 
    scope:
      path: "updates"
      type: "posts"
    values:
      layout: "update-layout"
      permalink: ":year/title"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
