### Toggle Switch
Code courtesy of Ananya Neogi
Source: https://dev.to/ananyaneogi/create-a-dark-light-mode-switch-with-css-variables-34l8
###

toggleSwitch = document.querySelector('.switcheroo input[type="checkbox"]')

switchTheme = (e) ->
  if e.target.checked
    document.documentElement.setAttribute 'data-theme', 'dark'
    localStorage.setItem 'theme', 'dark'
    #add this
  else
    document.documentElement.setAttribute 'data-theme', 'light'
    localStorage.setItem 'theme', 'light'
    #add this
  return

toggleSwitch.addEventListener 'change', switchTheme, false
currentTheme = localStorage.getItem('theme') or null
if currentTheme
  document.documentElement.setAttribute 'data-theme', currentTheme
  if currentTheme == 'dark'
    toggleSwitch.checked = true

# ---
# generated by js2coffee 2.2.0